# Standalone GNU Make build for the Fortran Time-Series Library.
# Generated by tools/generate_makefile.py. The committed file requires
# only GNU Make, a Fortran compiler, and an archiver to build.

FC = gfortran
AR = ar
FFLAGS = -O2
CPPFLAGS =
LDFLAGS =
LDLIBS =

BUILD_DIR ?= build-make
OBJ_DIR := $(BUILD_DIR)/obj
MOD_DIR := $(BUILD_DIR)/modules
BIN_DIR := $(BUILD_DIR)/bin
LIBRARY := $(BUILD_DIR)/libtime_series.a

ifeq ($(OS),Windows_NT)
  EXEEXT := .exe
else
  EXEEXT :=
endif

SOURCES := \
  kind.f90 \
  linalg.f90 \
  stats.f90 \
  spline.f90 \
  mixture.f90 \
  utils.f90 \
  calendar.f90 \
  fourier.f90 \
  special_functions.f90 \
  polynomial.f90 \
  random.f90 \
  distribution.f90 \
  resampling.f90 \
  optimization.f90 \
  distribution_fit.f90 \
  neural_network.f90 \
  recurrent_network.f90 \
  time_series_stats.f90 \
  rolling_forecast.f90 \
  time_series_var_utils.f90 \
  forecast.f90 \
  automatic_modeling.f90 \
  kfas.f90 \
  urca.f90 \
  astsa.f90 \
  itsmr.f90 \
  time_series_diagnostics.f90 \
  arima2.f90 \
  arfima.f90 \
  fracdiff.f90 \
  fracdist_tables.f90 \
  fracdist.f90 \
  nsarfima.f90 \
  garma.f90 \
  esemifar.f90 \
  tfarima.f90 \
  robustarima.f90 \
  mts.f90 \
  bayesforecast.f90 \
  bsts.f90 \
  bssm.f90 \
  tsss.f90 \
  tsissm.f90 \
  mar.f90 \
  fcvar.f90 \
  bigtime.f90 \
  bigvar.f90 \
  varshrink.f90 \
  vars.f90 \
  var_etp.f90 \
  bvartools.f90 \
  bvar.f90 \
  bvars.f90 \
  bvarsv.f90 \
  gmvarkit.f90 \
  ugmar.f90 \
  mswm.f90 \
  nts.f90 \
  tsdyn.f90 \
  expar.f90 \
  exparma.f90 \
  bentcablear.f90 \
  baystar.f90 \
  mixar.f90 \
  setartree.f90 \
  tseriestarma_tables.f90 \
  tseriestarma.f90 \
  gmdh.f90 \
  nnfor.f90 \
  narfima.f90 \
  nlints.f90 \
  tslstmplus.f90 \
  tsann.f90 \
  echos.f90 \
  starvars.f90 \
  rugarch.f90 \
  rugarch_extensions.f90 \
  rugarch_diagnostics.f90 \
  automatic_volatility.f90 \
  arma.f90 \
  long_memory.f90 \
  state_space.f90 \
  multivariate.f90 \
  volatility.f90 \
  spectral.f90 \
  diagnostics.f90 \
  forecasting.f90 \
  regression_time_series.f90 \
  bayesian_time_series.f90 \
  markov_switching.f90 \
  count_time_series.f90 \
  functional_time_series.f90

OBJECTS := $(addprefix $(OBJ_DIR)/,$(SOURCES:.f90=.o))

TEST_NAMES := \
  forecast \
  automatic_modeling \
  kfas \
  urca \
  astsa \
  random \
  mixture \
  calendar \
  spline \
  neural_network \
  itsmr \
  arima2 \
  arfima \
  fracdiff \
  fracdist \
  nsarfima \
  garma \
  esemifar \
  tfarima \
  robustarima \
  mts \
  bayesforecast \
  bsts \
  bssm \
  tsss \
  tsissm \
  mar \
  fcvar \
  bigtime \
  bigvar \
  varshrink \
  vars \
  var_etp \
  bvartools \
  bvar \
  bvars \
  bvarsv \
  gmvarkit \
  ugmar \
  mswm \
  nts \
  tsdyn \
  expar \
  exparma \
  bentcablear \
  baystar \
  mixar \
  setartree \
  tseriestarma \
  gmdh \
  nnfor \
  narfima \
  nlints \
  tslstmplus \
  tsann \
  echos \
  starvars \
  distribution \
  rugarch \
  automatic_volatility \
  facades

TEST_PROGRAMS := $(addprefix $(BIN_DIR)/test_,$(addsuffix $(EXEEXT),$(TEST_NAMES)))
RUN_TESTS := $(addprefix run-test-,$(TEST_NAMES))
EXAMPLE := $(BIN_DIR)/example_var2_fit$(EXEEXT)
PROGRAM := $(BIN_DIR)/ts_auto$(EXEEXT)

.PHONY: all programs examples tests test docs clean distclean

all: $(LIBRARY) $(PROGRAM)

programs: $(PROGRAM)

examples: $(EXAMPLE)

tests: $(TEST_PROGRAMS)

test: $(RUN_TESTS)

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(OBJ_DIR): | $(BUILD_DIR)
	mkdir $(OBJ_DIR)

$(MOD_DIR): | $(BUILD_DIR)
	mkdir $(MOD_DIR)

$(BIN_DIR): | $(BUILD_DIR)
	mkdir $(BIN_DIR)

$(OBJ_DIR)/%.o: %.f90 | $(OBJ_DIR) $(MOD_DIR)
	$(FC) $(CPPFLAGS) $(FFLAGS) -J$(MOD_DIR) -I$(MOD_DIR) -c $< -o $@

$(LIBRARY): $(OBJECTS) | $(BUILD_DIR)
	$(AR) rcs $@ $(OBJECTS)

$(BIN_DIR)/test_%$(EXEEXT): test_%.f90 $(LIBRARY) | $(BIN_DIR)
	$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@

run-test-%: $(BIN_DIR)/test_%$(EXEEXT)
	$<

$(EXAMPLE): examples/var2_fit.f90 $(LIBRARY) | $(BIN_DIR)
	$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@

$(PROGRAM): ts_auto.f90 $(LIBRARY) | $(BIN_DIR)
	$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@

docs:
	ford -q ford.md

clean:
	$(RM) $(OBJECTS) $(TEST_PROGRAMS) $(EXAMPLE) $(PROGRAM) $(LIBRARY)
	$(RM) $(MOD_DIR)/*.mod $(MOD_DIR)/*.smod

distclean: clean
	-rmdir $(BIN_DIR)
	-rmdir $(MOD_DIR)
	-rmdir $(OBJ_DIR)
	-rmdir $(BUILD_DIR)

# Explicit module-provider dependencies make parallel builds reliable.
$(OBJ_DIR)/linalg.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/stats.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o
$(OBJ_DIR)/spline.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/mixture.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/utils.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/fourier.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/special_functions.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o
$(OBJ_DIR)/polynomial.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/random.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o
$(OBJ_DIR)/distribution.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/resampling.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/optimization.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o
$(OBJ_DIR)/distribution_fit.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/distribution.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/neural_network.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/recurrent_network.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/time_series_stats.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/rolling_forecast.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/time_series_var_utils.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/forecast.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/rolling_forecast.o
$(OBJ_DIR)/automatic_modeling.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/forecast.o $(OBJ_DIR)/astsa.o
$(OBJ_DIR)/kfas.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o
$(OBJ_DIR)/urca.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o
$(OBJ_DIR)/astsa.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/kfas.o
$(OBJ_DIR)/itsmr.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/fourier.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/polynomial.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_stats.o
$(OBJ_DIR)/time_series_diagnostics.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/time_series_stats.o
$(OBJ_DIR)/arima2.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/random.o $(OBJ_DIR)/astsa.o
$(OBJ_DIR)/arfima.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/polynomial.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/arima2.o
$(OBJ_DIR)/fracdiff.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/fourier.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/arima2.o $(OBJ_DIR)/arfima.o
$(OBJ_DIR)/fracdist_tables.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/fracdist.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/fracdist_tables.o
$(OBJ_DIR)/nsarfima.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/fourier.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/arfima.o
$(OBJ_DIR)/garma.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/fourier.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/esemifar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/polynomial.o $(OBJ_DIR)/random.o $(OBJ_DIR)/arfima.o $(OBJ_DIR)/fracdiff.o
$(OBJ_DIR)/tfarima.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/calendar.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/kfas.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/time_series_diagnostics.o $(OBJ_DIR)/arima2.o
$(OBJ_DIR)/robustarima.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/tfarima.o
$(OBJ_DIR)/mts.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/urca.o
$(OBJ_DIR)/bayesforecast.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/bsts.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/calendar.o $(OBJ_DIR)/random.o $(OBJ_DIR)/kfas.o
$(OBJ_DIR)/bssm.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/kfas.o
$(OBJ_DIR)/tsss.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o $(OBJ_DIR)/forecast.o $(OBJ_DIR)/kfas.o
$(OBJ_DIR)/tsissm.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/forecast.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/time_series_diagnostics.o $(OBJ_DIR)/mts.o
$(OBJ_DIR)/mar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/fcvar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/fourier.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_diagnostics.o $(OBJ_DIR)/fracdist.o
$(OBJ_DIR)/bigtime.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_var_utils.o
$(OBJ_DIR)/bigvar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_var_utils.o $(OBJ_DIR)/bigtime.o
$(OBJ_DIR)/varshrink.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/vars.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/urca.o $(OBJ_DIR)/mts.o
$(OBJ_DIR)/var_etp.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/vars.o
$(OBJ_DIR)/bvartools.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_var_utils.o $(OBJ_DIR)/kfas.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/bssm.o
$(OBJ_DIR)/bvar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/bvars.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/mixture.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_var_utils.o $(OBJ_DIR)/bvartools.o
$(OBJ_DIR)/bvarsv.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/gmvarkit.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/ugmar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/random.o $(OBJ_DIR)/gmvarkit.o
$(OBJ_DIR)/mswm.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/nts.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/kfas.o $(OBJ_DIR)/bssm.o
$(OBJ_DIR)/tsdyn.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/spline.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/polynomial.o $(OBJ_DIR)/random.o $(OBJ_DIR)/neural_network.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/rolling_forecast.o $(OBJ_DIR)/nts.o
$(OBJ_DIR)/expar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/exparma.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/expar.o
$(OBJ_DIR)/bentcablear.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/polynomial.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/baystar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/mixar.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/time_series_diagnostics.o
$(OBJ_DIR)/setartree.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/tseriestarma_tables.o: $(OBJ_DIR)/kind.o
$(OBJ_DIR)/tseriestarma.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/tseriestarma_tables.o
$(OBJ_DIR)/gmdh.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o
$(OBJ_DIR)/nnfor.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/neural_network.o $(OBJ_DIR)/gmdh.o
$(OBJ_DIR)/narfima.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/random.o $(OBJ_DIR)/neural_network.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/arima2.o $(OBJ_DIR)/arfima.o $(OBJ_DIR)/bsts.o
$(OBJ_DIR)/nlints.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/urca.o
$(OBJ_DIR)/tslstmplus.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/recurrent_network.o
$(OBJ_DIR)/tsann.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/random.o $(OBJ_DIR)/time_series_stats.o $(OBJ_DIR)/nnfor.o
$(OBJ_DIR)/echos.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/random.o
$(OBJ_DIR)/starvars.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/utils.o $(OBJ_DIR)/calendar.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/optimization.o $(OBJ_DIR)/time_series_stats.o
$(OBJ_DIR)/rugarch.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/random.o $(OBJ_DIR)/distribution.o $(OBJ_DIR)/optimization.o
$(OBJ_DIR)/rugarch_extensions.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/random.o $(OBJ_DIR)/rugarch.o
$(OBJ_DIR)/rugarch_diagnostics.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/linalg.o $(OBJ_DIR)/stats.o $(OBJ_DIR)/special_functions.o $(OBJ_DIR)/distribution.o $(OBJ_DIR)/rugarch.o
$(OBJ_DIR)/automatic_volatility.o: $(OBJ_DIR)/kind.o $(OBJ_DIR)/rugarch.o
$(OBJ_DIR)/arma.o: $(OBJ_DIR)/utils.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/arima2.o $(OBJ_DIR)/tfarima.o $(OBJ_DIR)/robustarima.o $(OBJ_DIR)/ugmar.o $(OBJ_DIR)/nts.o $(OBJ_DIR)/tsdyn.o $(OBJ_DIR)/expar.o $(OBJ_DIR)/exparma.o $(OBJ_DIR)/baystar.o $(OBJ_DIR)/mixar.o $(OBJ_DIR)/setartree.o $(OBJ_DIR)/tseriestarma.o
$(OBJ_DIR)/long_memory.o: $(OBJ_DIR)/arfima.o $(OBJ_DIR)/fracdiff.o $(OBJ_DIR)/fracdist.o $(OBJ_DIR)/nsarfima.o $(OBJ_DIR)/esemifar.o $(OBJ_DIR)/narfima.o
$(OBJ_DIR)/state_space.o: $(OBJ_DIR)/kfas.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/tfarima.o $(OBJ_DIR)/bssm.o $(OBJ_DIR)/tsss.o $(OBJ_DIR)/bvartools.o $(OBJ_DIR)/nts.o
$(OBJ_DIR)/multivariate.o: $(OBJ_DIR)/urca.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/mar.o $(OBJ_DIR)/fcvar.o $(OBJ_DIR)/bigtime.o $(OBJ_DIR)/bigvar.o $(OBJ_DIR)/varshrink.o $(OBJ_DIR)/vars.o $(OBJ_DIR)/var_etp.o $(OBJ_DIR)/bvartools.o $(OBJ_DIR)/bvars.o $(OBJ_DIR)/bvarsv.o $(OBJ_DIR)/gmvarkit.o $(OBJ_DIR)/nts.o $(OBJ_DIR)/tsdyn.o $(OBJ_DIR)/mixar.o $(OBJ_DIR)/nlints.o $(OBJ_DIR)/starvars.o
$(OBJ_DIR)/volatility.o: $(OBJ_DIR)/distribution.o $(OBJ_DIR)/distribution_fit.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/bayesforecast.o $(OBJ_DIR)/tsissm.o $(OBJ_DIR)/bvartools.o $(OBJ_DIR)/tseriestarma.o $(OBJ_DIR)/starvars.o $(OBJ_DIR)/rugarch.o $(OBJ_DIR)/rugarch_extensions.o
$(OBJ_DIR)/spectral.o: $(OBJ_DIR)/fourier.o $(OBJ_DIR)/forecast.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/garma.o
$(OBJ_DIR)/diagnostics.o: $(OBJ_DIR)/forecast.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/time_series_diagnostics.o $(OBJ_DIR)/arfima.o $(OBJ_DIR)/garma.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/tsissm.o $(OBJ_DIR)/vars.o $(OBJ_DIR)/ugmar.o $(OBJ_DIR)/nts.o $(OBJ_DIR)/tsdyn.o $(OBJ_DIR)/mixar.o $(OBJ_DIR)/tseriestarma.o $(OBJ_DIR)/nlints.o $(OBJ_DIR)/echos.o $(OBJ_DIR)/starvars.o $(OBJ_DIR)/rugarch.o $(OBJ_DIR)/rugarch_diagnostics.o
$(OBJ_DIR)/forecasting.o: $(OBJ_DIR)/utils.o $(OBJ_DIR)/rolling_forecast.o $(OBJ_DIR)/forecast.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/itsmr.o $(OBJ_DIR)/arfima.o $(OBJ_DIR)/garma.o $(OBJ_DIR)/tfarima.o $(OBJ_DIR)/robustarima.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/bsts.o $(OBJ_DIR)/bssm.o $(OBJ_DIR)/bigtime.o $(OBJ_DIR)/bigvar.o $(OBJ_DIR)/var_etp.o $(OBJ_DIR)/bvartools.o $(OBJ_DIR)/ugmar.o $(OBJ_DIR)/tsdyn.o $(OBJ_DIR)/expar.o $(OBJ_DIR)/mixar.o $(OBJ_DIR)/setartree.o $(OBJ_DIR)/tseriestarma.o $(OBJ_DIR)/gmdh.o $(OBJ_DIR)/nnfor.o $(OBJ_DIR)/narfima.o $(OBJ_DIR)/nlints.o $(OBJ_DIR)/tslstmplus.o $(OBJ_DIR)/tsann.o $(OBJ_DIR)/echos.o $(OBJ_DIR)/starvars.o $(OBJ_DIR)/rugarch.o
$(OBJ_DIR)/regression_time_series.o: $(OBJ_DIR)/utils.o $(OBJ_DIR)/astsa.o $(OBJ_DIR)/arfima.o $(OBJ_DIR)/tfarima.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/bsts.o $(OBJ_DIR)/var_etp.o $(OBJ_DIR)/bentcablear.o $(OBJ_DIR)/mixar.o $(OBJ_DIR)/setartree.o $(OBJ_DIR)/tseriestarma.o $(OBJ_DIR)/tslstmplus.o
$(OBJ_DIR)/bayesian_time_series.o: $(OBJ_DIR)/astsa.o $(OBJ_DIR)/mts.o $(OBJ_DIR)/bayesforecast.o $(OBJ_DIR)/bsts.o $(OBJ_DIR)/bssm.o $(OBJ_DIR)/bvartools.o $(OBJ_DIR)/bvar.o $(OBJ_DIR)/bvars.o $(OBJ_DIR)/bvarsv.o $(OBJ_DIR)/baystar.o $(OBJ_DIR)/mixar.o
$(OBJ_DIR)/markov_switching.o: $(OBJ_DIR)/mswm.o $(OBJ_DIR)/nts.o
$(OBJ_DIR)/count_time_series.o: $(OBJ_DIR)/nts.o
$(OBJ_DIR)/functional_time_series.o: $(OBJ_DIR)/nts.o
