#!/usr/bin/env python3
"""Generate the standalone GNU Make build and Fortran module dependencies."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CMAKE_FILE = ROOT / "CMakeLists.txt"
MAKE_FILE = ROOT / "Makefile"


def cmake_block(text: str, start: str) -> list[str]:
    """Return whitespace-separated entries from one simple CMake block."""
    match = re.search(rf"{re.escape(start)}(.*?)\n\s*\)", text, re.DOTALL)
    if match is None:
        raise ValueError(f"CMake block not found: {start}")
    return match.group(1).split()


def logical_statements(text: str) -> list[str]:
    """Join free-form continuation lines sufficiently for module analysis."""
    statements: list[str] = []
    current = ""
    for raw_line in text.splitlines():
        line = raw_line.split("!", 1)[0].strip()
        if not line:
            continue
        if line.startswith("&"):
            line = line[1:].lstrip()
        continued = line.endswith("&")
        if continued:
            line = line[:-1].rstrip()
        current = f"{current} {line}".strip()
        if not continued:
            statements.append(current)
            current = ""
    if current:
        statements.append(current)
    return statements


def source_modules(path: Path) -> tuple[set[str], set[str]]:
    """Return modules defined and used by one Fortran source file."""
    definitions: set[str] = set()
    uses: set[str] = set()
    for statement in logical_statements(path.read_text(encoding="utf-8")):
        module_match = re.match(
            r"module\s+(?!procedure\b|subroutine\b|function\b)([a-z]\w*)",
            statement,
            re.IGNORECASE,
        )
        if module_match:
            definitions.add(module_match.group(1).lower())
        use_match = re.match(
            r"use(?:\s*,\s*[^:]*)?\s*(?:::)?\s*([a-z]\w*)",
            statement,
            re.IGNORECASE,
        )
        if use_match:
            uses.add(use_match.group(1).lower())
    return definitions, uses


def wrapped_assignment(name: str, values: list[str]) -> list[str]:
    """Format a readable multiline GNU Make variable assignment."""
    if not values:
        return [f"{name} :="]
    lines = [f"{name} := \\"]
    for index, value in enumerate(values):
        suffix = " \\" if index + 1 < len(values) else ""
        lines.append(f"  {value}{suffix}")
    return lines


def generate() -> str:
    """Generate a CMake-free GNU Make build from the maintained target lists."""
    cmake = CMAKE_FILE.read_text(encoding="utf-8")
    sources = cmake_block(cmake, "add_library(time_series STATIC")
    tests = cmake_block(cmake, "foreach(test_name IN ITEMS")

    providers: dict[str, str] = {}
    uses_by_source: dict[str, set[str]] = {}
    modules_by_source: dict[str, set[str]] = {}
    for source in sources:
        definitions, uses = source_modules(ROOT / source)
        modules_by_source[source] = definitions
        uses_by_source[source] = uses
        for module in definitions:
            if module in providers:
                raise ValueError(f"module {module} has multiple providers")
            providers[module] = source

    dependencies: dict[str, set[str]] = {}
    for source in sources:
        dependencies[source] = {
            providers[module]
            for module in uses_by_source[source]
            if module in providers and providers[module] != source
        }

    lines = [
        "# Standalone GNU Make build for the Fortran Time-Series Library.",
        "# Generated by tools/generate_makefile.py. The committed file requires",
        "# only GNU Make, a Fortran compiler, and an archiver to build.",
        "",
        "FC = gfortran",
        "AR = ar",
        "FFLAGS = -O2",
        "CPPFLAGS =",
        "LDFLAGS =",
        "LDLIBS =",
        "",
        "BUILD_DIR ?= build-make",
        "OBJ_DIR := $(BUILD_DIR)/obj",
        "MOD_DIR := $(BUILD_DIR)/modules",
        "BIN_DIR := $(BUILD_DIR)/bin",
        "LIBRARY := $(BUILD_DIR)/libtime_series.a",
        "",
        "ifeq ($(OS),Windows_NT)",
        "  EXEEXT := .exe",
        "else",
        "  EXEEXT :=",
        "endif",
        "",
    ]
    lines.extend(wrapped_assignment("SOURCES", sources))
    lines.extend(
        [
            "",
            "OBJECTS := $(addprefix $(OBJ_DIR)/,$(SOURCES:.f90=.o))",
            "",
        ]
    )
    lines.extend(wrapped_assignment("TEST_NAMES", tests))
    lines.extend(
        [
            "",
            "TEST_PROGRAMS := $(addprefix $(BIN_DIR)/test_,$(addsuffix $(EXEEXT),$(TEST_NAMES)))",
            "RUN_TESTS := $(addprefix run-test-,$(TEST_NAMES))",
            "EXAMPLE := $(BIN_DIR)/example_var2_fit$(EXEEXT)",
            "PROGRAM := $(BIN_DIR)/ts_auto$(EXEEXT)",
            "",
            ".PHONY: all programs examples tests test docs clean distclean",
            "",
            "all: $(LIBRARY) $(PROGRAM)",
            "",
            "programs: $(PROGRAM)",
            "",
            "examples: $(EXAMPLE)",
            "",
            "tests: $(TEST_PROGRAMS)",
            "",
            "test: $(RUN_TESTS)",
            "",
            "$(BUILD_DIR):",
            "\tmkdir $(BUILD_DIR)",
            "",
            "$(OBJ_DIR): | $(BUILD_DIR)",
            "\tmkdir $(OBJ_DIR)",
            "",
            "$(MOD_DIR): | $(BUILD_DIR)",
            "\tmkdir $(MOD_DIR)",
            "",
            "$(BIN_DIR): | $(BUILD_DIR)",
            "\tmkdir $(BIN_DIR)",
            "",
            "$(OBJ_DIR)/%.o: %.f90 | $(OBJ_DIR) $(MOD_DIR)",
            "\t$(FC) $(CPPFLAGS) $(FFLAGS) -J$(MOD_DIR) -I$(MOD_DIR) -c $< -o $@",
            "",
            "$(LIBRARY): $(OBJECTS) | $(BUILD_DIR)",
            "\t$(AR) rcs $@ $(OBJECTS)",
            "",
            "$(BIN_DIR)/test_%$(EXEEXT): test_%.f90 $(LIBRARY) | $(BIN_DIR)",
            "\t$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@",
            "",
            "run-test-%: $(BIN_DIR)/test_%$(EXEEXT)",
            "\t$<",
            "",
            "$(EXAMPLE): examples/var2_fit.f90 $(LIBRARY) | $(BIN_DIR)",
            "\t$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@",
            "",
            "$(PROGRAM): ts_auto.f90 $(LIBRARY) | $(BIN_DIR)",
            "\t$(FC) $(CPPFLAGS) $(FFLAGS) -I$(MOD_DIR) $(LDFLAGS) $< $(LIBRARY) $(LDLIBS) -o $@",
            "",
            "docs:",
            "\tford -q ford.md",
            "",
            "clean:",
            "\t$(RM) $(OBJECTS) $(TEST_PROGRAMS) $(EXAMPLE) $(PROGRAM) $(LIBRARY)",
            "\t$(RM) $(MOD_DIR)/*.mod $(MOD_DIR)/*.smod",
            "",
            "distclean: clean",
            "\t-rmdir $(BIN_DIR)",
            "\t-rmdir $(MOD_DIR)",
            "\t-rmdir $(OBJ_DIR)",
            "\t-rmdir $(BUILD_DIR)",
            "",
            "# Explicit module-provider dependencies make parallel builds reliable.",
        ]
    )
    for source in sources:
        deps = sorted(dependencies[source], key=sources.index)
        if not deps:
            continue
        target = f"$(OBJ_DIR)/{Path(source).stem}.o"
        prereqs = " ".join(f"$(OBJ_DIR)/{Path(dep).stem}.o" for dep in deps)
        lines.append(f"{target}: {prereqs}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    """Write the standalone Makefile at the repository root."""
    MAKE_FILE.write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    main()
